### ISSUE TITLE
Correct Audio file name

### ISSUE THREAD

**Issue by Vaaai** [emesterhazy/glossika-to-anki#10]
First of all, thank you for this great project!! 
I'm stuck on the audio script that tells me to refer to the readme for the correct file name pattern. Unfortunately,  I cannot find any hint on that in the actual readme. So my question would be what the actual file name for the audio files has to be? Additionally, am I right assuming to put the audio files into the glossika_source/audio folder? 

Thank you very much for your help and time!

**Comment by emesterhazy** [comment]
Hi! You'll want to use the `C` version audio files which speak each sentence once in the language you're learning.

Here's an example of what the filename looks like for Mandarin:
```
ENZS-F1-GMS-C-0001.mp3
```

The first part (`ENZS`) denotes English - Mandarin. The second part denotes the section. GMS just stands for "Glossika mass sentences", and 0001 denotes the track number. Hope that helps!

**Comment by emesterhazy** [comment]
Closing this due for now. Please feel free to re-open if you are still having trouble. Thanks!
