### ISSUE TITLE
ImportError: No module named cv2

### ISSUE THREAD

**Issue by Apetited** [emesterhazy/glossika-to-anki#11]
I don't think this is a problem with the script, but I'm getting this error message. I've tried installing OpenCV using both homebrew and Pip but Python still can't access the module. Any advice would be appreciated. I'm using a Mac.

**Comment by emesterhazy** [comment]
Can you post the exact stack trace you're seeing? Thanks!

**Comment by emesterhazy** [comment]
Please feel free to reopen with more details if you are still having this issue :)
