### ISSUE TITLE
Cantonese Level 1 - PDF to TSV extraction missing sentences

### ISSUE THREAD

**Issue by awhlam** [emesterhazy/glossika-to-anki#16]
I ran the PDF to TSV extraction for Cantonese.

Levels 2 and 3 extracted all 1,000 sentences fine, but level 1 was missing 3 sentences in the output TSV (I modified the Python script to not abort).

Below is an example of a sentence that was missed:

Glossika PDF
![Capture](https://user-images.githubusercontent.com/32132177/115803213-4c455980-a395-11eb-85ab-c410a788e41e.JPG)

Output TSV Extraction:
![Capture2](https://user-images.githubusercontent.com/32132177/115803369-92022200-a395-11eb-8cd4-41258c14bc7c.JPG)

Sentence #89 - has the Yale for sentence #90 instead
Sentence #90 is missing

I think it might be an issue with the regular expressions? Let me know if you have any ideas or if you need more examples.

**Comment by awhlam** [comment]
The other two missing sentences have a similar issue as above:

Sentence #253 - Are you sitting on the floor?
Sentence #255 - Are you feeling all right?

**Comment by emesterhazy** [comment]
Could you run `pdftotext` on the PDF and share a snippet that includes the missing sentences?

The command should be something like
```
pdftotext -layout -enc UTF-8 file_name.pdf output.txt
```

**Comment by awhlam** [comment]
@emesterhazy - Sure, [here is the snippet](https://pastebin.com/nJPAQg3E) of the `pdftotext` output that corresponds with the screenshot in my first post above.
- It looks like sentence #89 has the translations shifted down by one line.
- Sentences #90-91 look ok to me in this output.

**Comment by emesterhazy** [comment]
Closing due to archival of project. Best of luck!
