### ISSUE TITLE
README.md Instructions Clarification

### ISSUE THREAD

**Issue by MalikMAlna** [emesterhazy/glossika-to-anki#7]
Hey, under “Requirements and Setup” you said for the Xpdf tools that one would need “copy pdftotext.exe to a folder on the path (i.e. the Python folder)” and a friend of mine and I who wish to setup the program are not sure which python folder you are referring to here. Could you please clarify this statement and provide an example what the default path may look like on a Windows machine.

Additionally, I can submit a pull request to add the explanation to the README.md after you’ve explained so you don’t have to do so twice. I’m a new developer interested in providing his first open source contribution, and I would appreciate the opportunity to help with your project in whatever way I can.

**Comment by emesterhazy** [comment]
Hi, glad to see you're finding this useful. Here's a few links I found that might be relevant:

1. [How to change the path on windows](https://www.java.com/en/download/help/path.xml)
2. [Python installation - adding python to the path](https://docs.python.org/3/using/windows.html#finding-the-python-executable)

If you installed python with the Windows installer it looks like it should be located in `C:\Program Files` or `C:\Users\your_name\AppData\Local`. You might also be able to run `which python` or `where python` from cmd prompt to figure out where the python executable is located.

I can check later this week on a windows computer if you're having issues getting things to work.

Cheers :)

**Comment by MalikMAlna** [comment]
Hey, thanks for getting back with me so quickly. Sorry it took me a while to get back with you on this issue. I've been a bit busy with the holiday season. My friend and I found the information you provided here to be quite helpful.

 However, my friend isn't particularly comfortable with a terminal or command prompt. Specifically, the instructions on using "genanki to generate Anki decks" is where he's running into trouble. Is there a different way that one can go about generating decks outside of using a terminal or command prompt? If not, I can probably guide him through the process despite his apprehension using a terminal emulator (I'm more comfortable with that as opposed to a command prompt myself), but I just wanted to make sure there weren't any other things we could try in his case.

Thanks again for your help, and have a wonderful holiday season!

**Comment by emesterhazy** [comment]
Unfortunately there isn't a way to generate the decks without using the command line. That said, it's actually pretty easy to use the scripts so hopefully you can walk your friend through the process.
